[package]
name = "ocr"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
dotenvy.workspace = true
futures-util.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "process", "rt-multi-thread", "time"] }

[features]
testing = []

[dev-dependencies]
ocr = { workspace = true, features = ["testing"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "time"] }
