[package]
name = "graph"
version.workspace = true
edition.workspace = true

[dependencies]
falkordb.workspace = true
rag-core.workspace = true
thiserror.workspace = true

[features]
testing = []

[dev-dependencies]
graph = { workspace = true, features = ["testing"] }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
